#!/usr/bin/env ruby
repo='sickp/alpine-sshd'

def error(message)
  puts message
  puts "Usage: #{__FILE__} {major}.{minor}"
  exit 1
end

def execute(cmd)
  puts "=> #{cmd}"
  system(cmd) || abort
end

version = ARGV.first
error("Bad version format: #{version}") unless version&.match?(/\A\d+\.\d+\z/)

dockerfile = File.join(File.dirname(__FILE__), 'versions', version, 'Dockerfile')
error("Missing Dockerfile #{dockerfile}") unless File.file?(dockerfile)

execute("docker image build --tag #{repo}:#{version} --pull versions/#{version}")
