#!/usr/bin/env ruby
repo="sickp/alpine-sshd"

sshd_version = ARGV.first
unless File.file?("versions/#{sshd_version}/Dockerfile")
  puts "Usage: build <sshd-version>"
  exit 1
end

system("docker build -t #{repo}:#{sshd_version} --pull versions/#{sshd_version}") || abort
puts "Built #{repo}:#{sshd_version}"

system("docker tag #{repo}:#{sshd_version} #{repo}:latest") || abort
puts "Tagged #{repo}:latest"
