#!/usr/bin/env ruby
repo='sickp/alpine-sshd'

def error(message)
  puts message
  puts "Usage: #{__FILE__} {major}.{minor} [latest]"
  exit 1
end

def execute(cmd)
  puts "=> #{cmd}"
  system(cmd) || abort
end

version, *tags = ARGV
error("Bad version format: #{version}") unless version&.match?(/\A\d+\.\d+(-r\d+)?\z/)
error("Unexpected tags: #{tags.join(', ')}") unless tags.empty? || (tags.first == 'latest')

dockerfile = File.join(File.dirname(__FILE__), 'versions', version, 'Dockerfile')
error("Missing Dockerfile #{dockerfile}") unless File.file?(dockerfile)

puts "==== Pushing #{repo}:#{version} ===="
execute("docker image push #{repo}:#{version}")

tags.each do |tag|
  puts "==== Tagging #{repo}:#{tag} ===="
  execute("docker image tag #{repo}:#{version} #{repo}:#{tag}")
  execute("docker image push #{repo}:#{tag}")
  execute("docker image rm #{repo}:#{tag}")
end
