#!/usr/bin/env ruby
repo="sickp/alpine-sshd"

sshd_version = ARGV.first
unless File.file?("versions/#{sshd_version}/Dockerfile")
  puts "Usage: build <sshd-version>"
  exit 1
end

[sshd_version, "latest"].each do |tag|
  system("docker push #{repo}:#{tag}") || abort
  puts "Pushed #{repo}:#{tag}"
end
